//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xamarin.Windows.Properties.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xamarin.Windows.Properties.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional AOT Options.
        /// </summary>
        public static string AdditionalAotOptions {
            get {
                return ResourceManager.GetString("AdditionalAotOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mono Command Line Options.
        /// </summary>
        public static string AdditionalMonoOptions {
            get {
                return ResourceManager.GetString("AdditionalMonoOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments --debug --debugger-agent=transport=dt_socket,address=127.0.0.1:&lt;port&gt; will be added automatically..
        /// </summary>
        public static string AdditionalMonoOptionsHelpText {
            get {
                return ResourceManager.GetString("AdditionalMonoOptionsHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AOT Compilation.
        /// </summary>
        public static string AotMode {
            get {
                return ResourceManager.GetString("AotMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AOT Compilation Enabled.
        /// </summary>
        public static string AotModePropertyName {
            get {
                return ResourceManager.GetString("AotModePropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundle Assemblies.
        /// </summary>
        public static string BundleAssemblies {
            get {
                return ResourceManager.GetString("BundleAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debuggable Assemblies.
        /// </summary>
        public static string GenerateDebuggableAotModules {
            get {
                return ResourceManager.GetString("GenerateDebuggableAotModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JIT Compilation.
        /// </summary>
        public static string JitMode {
            get {
                return ResourceManager.GetString("JitMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JIT Compilation Enabled.
        /// </summary>
        public static string JitModePropertyName {
            get {
                return ResourceManager.GetString("JitModePropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More info about.
        /// </summary>
        public static string MonoLoggingHelpText {
            get {
                return ResourceManager.GetString("MonoLoggingHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging Mono Runtime Events.
        /// </summary>
        public static string MonoLoggingLinkHelpText {
            get {
                return ResourceManager.GetString("MonoLoggingLinkHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mono trace level (MONO_LOG_LEVEL).
        /// </summary>
        public static string MonoLogLevel {
            get {
                return ResourceManager.GetString("MonoLogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mono trace filters (MONO_LOG_MASK).
        /// </summary>
        public static string MonoLogMask {
            get {
                return ResourceManager.GetString("MonoLogMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xamarin.
        /// </summary>
        public static string OptionsTitle {
            get {
                return ResourceManager.GetString("OptionsTitle", resourceCulture);
            }
        }
    }
}
